server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
telegram:
  bot:
    name: News_recommendations_bot
    token: 7738264458:AAEf1mmSBXFdFWS6SjYvfnvYxfe9vvZn4HU