server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
telegram:
  bot:
    name: News_recommendations_bot
    token: 7738264458:AAEf1mmSBXFdFWS6SjYvfnvYxfe9vvZn4HU

spring:
  flyway:
    schemas: public
  application:
    name: HomeWork
  datasource:
    url: jdbc:postgresql://localhost:5432/postgress
    username: postgress
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
